font_family      SF Mono
bold_font         SF Mono
italic_font       SF Mono
bold_italic_font  SF Mono
font_size 10

background #1b1928
foreground #bcb5c8
selection_background #31293b
selection_foreground #bcb5c8

cursor #a49bb1
cursor_text_color #1b1928

color0 #1b1928
color1 #8e6059
color2 #5a8568
color3 #9e8558
color4 #5f7a9e
color5 #7c7689
color6 #5f9e9e
color7 #a49bb1

color8 #45415a
color9 #b08080
color10 #7daa8a
color11 #c4a878
color12 #8ba4c7
color13 #a49bb1
color14 #8fc4c4
color15 #bcb5c8

background_opacity 0.85

enable_audio_bell no

confirm_os_window_close 0

hide_when_typing no
